---
- name: Ensure SSH key is copied to the root user
  ansible.builtin.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/{{ ssh_mgmt_key }}.pub') }}"  # Path to your SSH public key
  when: ansible_facts['virtualization_type'] != 'lxc' # only when not LXC  

- name: Update and upgrade the system
  include_tasks: ../../tasks/update_system.yml
  when: hostvars[inventory_hostname].upgrade

# - name: Debug
#   include_tasks: ../../tasks/debug.yml

# - name: Debug the packages variable
#   debug:
#     var: packages    

- name: Ensure extra packages are installed and upgraded
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Print user_create variable from hostvars
  ansible.builtin.debug:
    msg: "The value of user_create is: {{ hostvars[inventory_hostname].user_create }}"

- name: Create non-root user
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    groups: sudo
    append: true
  when: hostvars[inventory_hostname].user_create is defined and hostvars[inventory_hostname].user_create

- name: Ensure public SSH key is copied to the non-root user
  ansible.builtin.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/{{ ssh_mgmt_key }}.pub') }}"
  when: hostvars[inventory_hostname].user_create is defined and hostvars[inventory_hostname].user_create
