all:
  vars:
    # Defaults can be overriden by group or host
    user_create: true # create a non-root user
    users: # users to create
      - will
    user_password: $USER_PASSWORD # password for non-root user(s)
    source_user: will # user to copy SSH keys from
    ansible_user: root # default user to connect to target host
    upgrade: true
    chezmoi_version: "" # will use latest if not specified
    ssh_mgmt_key: /Users/will/.ssh/id_rsa
    ssh_github_key: id_github
    github_clone: false
    github_user: willquill
    github_repo: homelab
    github_email: 4646219+willquill@users.noreply.github.com
    # FIXME: Use these maybe?
    #ansible_become_pass: "{{ vault_ansible_become_pass }}"
    #ansible_sudo_pass: "{{ vault_ansible_become_pass }}"
    #ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"

servers:
  hosts:
    bespin:
      upgrade: false
    hoth:
      upgrade: false
    endor:
      upgrade: false

workstations:
  hosts:
    tweed:

services:
  hosts:
    photos:
      ansible_ssh_host: 10.1.20.21
      github_clone: true
    homelab:
      ansible_ssh_host: 10.1.20.22
      upgrade: false
      github_clone: true
    frigate:
      user_create: false
      ansible_user: root
      ansible_ssh_host: 10.1.20.23
      github_clone: true
    paperless:
      ansible_ssh_host: 10.1.20.24
      github_clone: true
    plex:
      ansible_ssh_host: 10.1.20.25
      upgrade: false
    photoprism:
      ansible_ssh_host: 10.1.20.27
      github_clone: true
    lancache:
      ansible_ssh_host: 10.1.20.28
      github_clone: true
    kopia:
      ansible_ssh_host: 10.1.20.29
      upgrade: false
      github_clone: true
    secrets:
      ansible_ssh_host: 10.1.20.31
      github_clone: true
    # test:
    #   ansible_ssh_host: 10.1.20.33
    #   github_clone: true
