all:
  vars:
    # Defaults can be overriden by group or host
    user_create: true # create a non-root user
    user_name: will # name of user to create
    src_ssh_key: ~/.ssh/id_rsa.pub # public SSH key to copy to target host
    ansible_user: root # default user to connect to target host
    upgrade: true
    local_key: id_rsa
    github_key: id_github
    github_user: willquill
    github_repo: homelab
    github_email: 4646219+willquill@users.noreply.github.com
    # FIXME: Use these maybe?
    #ansible_become_pass: "{{ vault_ansible_become_pass }}"
    #ansible_sudo_pass: "{{ vault_ansible_become_pass }}"
    #ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"

servers:
  hosts:
    hoth:
      upgrade: false

workstations:
  hosts:
    micropop:
      
docker:
  hosts:
    photos:
      ansible_ssh_host: 10.1.20.21
    homelab:
      ansible_ssh_host: 10.1.20.22
      upgrade: false
    frigate:
      user_create: false
      ansible_user: root
      ansible_ssh_host: 10.1.20.23
    paperless:
      ansible_ssh_host: 10.1.20.24
    plex:
      ansible_ssh_host: 10.1.20.25
      upgrade: false
    photoprism:
      ansible_ssh_host: 10.1.20.27
    lancache:
      ansible_ssh_host: 10.1.20.28
    kopia:
      ansible_ssh_host: 10.1.20.29
      upgrade: false
    ansible-test:
      ansible_ssh_host: 10.1.20.31
   