---
- name: Install and Configure Samba Server
  hosts: samba
  #remote_user: will

  # become root user, which is needed for most tasks
  become: yes
  become_method: sudo
  #gather_facts: no

  vars_files:
    - vars/main_vars.yml

  handlers:
    - name: restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted

  tasks:
    - name: Install generic needed packages
      apt:
        name:
          - software-properties-common
          - dkms
        state: latest
        cache_valid_time: 3600

    #- import_tasks: tasks/setupZFStask.yml
    - import_tasks: tasks/setupUsersTask.yml
    - import_tasks: tasks/setupSambaTask.yml
    #- import_tasks: tasks/setupDocker.yml
