- name: Download Docker installation script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: Run Docker installation script
  ansible.builtin.shell:
    cmd: "sh /tmp/get-docker.sh"
  register: docker_install_output

- name: Show Docker installation script output
  ansible.builtin.debug:
    msg: "{{ docker_install_output.stdout }}"
